### ISSUE TITLE
0.3.0 s4m object doesn't load on Big Sur

### ISSUE THREAD

**Issue by plaukiu** [iainctduncan/scheme-for-max#128]
[bpatcher s4m.repl] loads and works ok. [s4m] loads orange.
[s4m] of 0.2.0 works ok.

I don't know how to debug.

**Comment by iainctduncan** [comment]
Ah damn, that's unfortunate, as I do not have Big Sur. Thanks very much for reporting this. I'm glad 0.2 works fine, and will see if I can figure out what might be doing it.

**Comment by rsj-stevenson** [comment]
It's working for me on MacOS 11.6/Intel Mac Mini apart for some crashes when running the "scan" command which I'll report separately.

**Comment by iainctduncan** [comment]
we are working on this now, sorry for the delay...

**Comment by iainctduncan** [comment]
Great, thanks for the update./
