### ISSUE TITLE
implement thread first and thread last macros

### ISSUE THREAD

**Issue by iainctduncan** [iainctduncan/scheme-for-max#17]
implement the clojure-style -> and ->> thread first and thread last macros so we can build compound statements in simple max messages, like:
foo 1 2 -> + 10 ->> out 1

**Comment by iainctduncan** [comment]
Jon Arkell has got it working, he may improve it so will leave this open

**Comment by lassik** [comment]
See also [SRFI 197: Pipeline Operators](https://srfi.schemers.org/srfi-197/srfi-197.html).

**Comment by iainctduncan** [comment]
closing as haven't found any issues yet with Jon's implementation
