### ISSUE TITLE
0.1.5-beta crashes on start on OS X

### ISSUE THREAD

**Issue by shakfu** [iainctduncan/scheme-for-max#62]
Hey cool project!

Just tried 0.15-beta release and it gives an error right after instantiating the [s4m] object in the Max 8 patch screen (Max OS X, Mojave 10.14.6):
```
s4m: Bootstrapping s4m.scm
s4m: s4m Error loading /Volumes/XXX/Users/YYY/Documents/Max 8/Packages/Scheme-For-Max/patchers/s4m.scm: 
;unbound variable cm/loop.scm
;    (lambda (code) (if (tree-cyclic?...
```

**Comment by iainctduncan** [comment]
Hi! Thanks for the issue and interest, I was debugging this today actually, I mucked it up trying to do the windows release. There should be a fix up today and I will comment when it's up. In the meantime, if you want, you should be able to make it go by commenting out the lines s4m.scm that load loop.scm and utilities.scm.

**Comment by shakfu** [comment]
Thanks that worked!

**Comment by iainctduncan** [comment]
Hi, the 0.1.6 beta release (just put it up) fixes those issues. It includes the common music files "loop.scm" and "utilities.scm", but doesn't load them by default anymore as loop is apparently mucked up on windows. on OSX the loop macro works and can be enabled by uncommenting that line in s4m.scm. 

I'm going to close this ticket as I know the issue you hit was addressed, but please open more or post to the goggle group if you find more!
