### ISSUE TITLE
output list starts with a symbol has no effect on max object

### ISSUE THREAD

**Issue by larme** [iainctduncan/scheme-for-max#63]
When using something like `(out 0 (list 'max 10))`, the output message has no effect on max object receiving the message. It's easier to explain by look at the example I provided.

I'm on macOS, max 8.1.3 and s4m 0.1.6 beta.

<pre><code>
----------begin_max5_patcher----------
973.3oc0XssaaBCF95jmBKzjViTZjs47tZuGKSQ.wMkNvDYLoYppu6yGf1zV
SiEPS6xEf7er8m+9OadX9LmzpijZGvO.+BLa1CymMSIRJXV63YNkIGyJRpUS
yIqprjP4NK0+GmbjqjiVA3MLJnhB3U61UPVSwq.YE4Y+AjlP2sl5tBbeBO6V
.+VBXa9M2PXhMBjRtM4PdECTcCHqpgxIr5tcuHmRTxjP30JLeqBvpz6tFG1M
y8xcNmtaCijw07wEiWAWBB7jOQ9P0.wSvuaWCsoLmVP3JhgdVXUCuSJTJ7w4
ykOVZoFpjTWmri7FMTMgC9Fxw.K76DpQl+28DMEbbd5vZffdggRNg8Uu7PpA
39HH1HAQCffTx8hi8a32dFYOgt0DAcGHAQJl4BUTy288IHZxHXeVPwj.HnIB
hGFA8g3U9BBFn7T0tne9VP.4PRw00bl3vZfrnnQYMQg5.RD5RYN6gs0dkfeJ
15Z.1DKi6mkKsioXju7UX7PHZmwtN4.Y6FwIRr6aR3BiRZCWmxd1S7Ubxomt
WpCsdaTiUJroJJXsyUojc4TvUBP.Hv2EqZgd.DbUQdsPHbwhEqcLEofFmyim
JRACubI6ZJSILSNHAOW6gkTRD0s1PnIoEJ9.eOmGY8PaXqGL1l7B83.McQJs
kkMGmD1qAMW1lPa3xR8Pax1qSFFbFKruQR6cIx1iFX85PeUxd6LpeUR1OvR2
n.c7ZT7Wlj8lXGdTrC6pLhtCibSSBdzvSvKvgWQMoVPCJ01YSq0p1h05Kutm
OsjzcYUEUL8jgqhBN8W3RoHOWjaH12KFhhCPRQPbnmOLNB5FKJ3JlE5B3j0W
QgnOtZBsJu+GpIDLUkDZ47EujPObVXPYUBUuohB8WS3rVVWbvI4JCbuTEFz2
S2.W7FjW74LlczrsEtyF9GzESGDEHhwUw5sA9vPYh.yhPed2OTzY7ocA+ccG
D80I73Jrp0hH7n8VTqS8kVd02ARAtT9K0D0UMrrtiZazN3Yz2Rp44zDdtnxx
yyIROGi5Zaww2Bbd4Yohskv52HOk.KaC1DxvQgrmEH6OApVrMTT9UbFORt1f
jH1PbwxIVYZEz8YGGmGj7VumG5oHHAaCPSggT98QNwF0igzepP5h3b1YAdes
W7TfTnMHELEHYkWOdJPBO7DzvOdjk2Z2TRkwEYirIx9Ug+SEqsB5ymNS2.Px
98GHr51Uq.Uzzyc51whVpFlS0CUcR4vHGx6luqRRBSzsBWzpRCScPcNFnakz
orR.LsIuEaAcEPpZnhJZvrdehlYp9tl+37+AEHGEwB
-----------end_max5_patcher-----------
</code></pre>

**Comment by iainctduncan** [comment]
Hey

**Comment by iainctduncan** [comment]
Oops that close was by accident. What I meant to do was ask if you would be willing to test a fix from an external build before I make a release?

**Comment by larme** [comment]
Sure. Just mail me at dev@zsy.im.

**Comment by iainctduncan** [comment]
Ok great, I'll make a bug fix release tomorrow and be in touch!

**Comment by iainctduncan** [comment]
Hi Larme, email didn't like my file, so I put it up for releases for you to test. Let me know if that works

**Comment by larme** [comment]
Hi Iain,

In my test this release fix the problem. Thanks a lot!

**Comment by iainctduncan** [comment]
Great, will close and include this in the next release
