### ISSUE TITLE
Solve the Halting Problem

### ISSUE THREAD

**Issue by jonnay** [iainctduncan/scheme-for-max#92]
A mis-step in recursion will just make max pin the CPU, and the only way to stop is to force-quit.   Since recursion is one of the natural ways to problem-solve in scheme, it'd be nice if making a mistake wasn't fatal (at least to the max process)

Maybe a maximum stack depth?  Maybe a maximum execution time?  

Repro:
```
((lambda (x) (x x)) (lambda (x) (x x)))
```

**Comment by iainctduncan** [comment]
Hmm, that's a really good point. It could be tricky to solve, but yeah, lots of people are going to hit it. I'll do some experimenting and digging. So you couldn't even reset the interpreter, Max just locks up?

**Comment by jonnay** [comment]
Yeah, Max just locks up.  Fun fact.  After killing max, after you try and restore max just locks up again!

**Comment by lassik** [comment]
Do all s7 applications have this problem, and would bil be willing to solve this directly in s7 by adding a hook to interrupt a running program?

**Comment by iainctduncan** [comment]
Hi Lassi! Yeah, that's what I need to find out. I'll post on the CM mailing list later today and see what Bill's thoughts are there. I also want to check whether the same thing happens with the js object, it might have to be a "just be careful" thing for now. There may be a way in max to kill an object's work too, but I don't think I've seen it in the SDK docs yet.

**Comment by iainctduncan** [comment]
@jonnay I determined that we get the same behaviour js object, in that an eternal loop locks up Max and one has to force quit. So I think if it turns out there is a decent way to limit it from the S7, it's reasonable to do so, but if not, might have to just be a warning in the docs!

**Comment by iainctduncan** [comment]
Here's what I got from Bill on the CMdist list, so it's not sounding like there is a good fix for this. 
"You can set (*s7* 'max-stack-size) which will raise an
error if the stack gets beyond that size.  Tail recursion
does not affect the stack, so the stack-max-size only
catches "normal" infinite recursion.  I don't know the
context, but in nrepl I trap SIGINT (control-C) and
raise an error in the interrupt handler -- look for
set_sigint_handler and related code in nrepl.c.  This
is then enabled during s7_eval_string in nrepl.scm.
I just noticed (of course!) that it only works once --
not sure why you can't interrupt successive expressions.
Snd (and maybe Grace) use s7's begin_hook to interrupt
computation, but that slows down everything (it is
polling the begin_hook and calling a function each time)
and might not work in loops that the optimizer has
so tightly optimized that no scheme-level body exists."

**Comment by lassik** [comment]
Would it work to run s7 in a separate thread, and use a control thread to start/stop the s7 thread on demand?

I'm not sure how you'd reload the interpreter state if you restart the s7 thread though. And how to GC everything if you need to stop it mid-computation.

**Comment by iainctduncan** [comment]
Closing this as it seems to rarely affect things and is normal behaviour in Max anyway (as in, you can make Max lockup if you want with infinite loops and so on.) Having dug further into threads in max, I'm sure we definitely do not want to add threading here.
