### ISSUE TITLE
Double clicking on a s4m node tries to open javascript

### ISSUE THREAD

**Issue by jonnay** [iainctduncan/scheme-for-max#93]
Expected action: Nothing, or even cooler open up the file dialog for choosing a scheme file

Actual Action: opens the os file dialog with only js files allowed to be selected.

If you don't provide a file extension to s4m it'll also try and load a js file.

**Comment by iainctduncan** [comment]
Hi Jon, are you on Windows? I don't get this behaviour on OSX.

**Comment by jonnay** [comment]
Ohhh, I think the problem is this:

I have "foo.js" in the max path, as well as "foo.scm".

**Comment by iainctduncan** [comment]
Ah, hmm, that sounds like what's up. But details on how to improve this area most welcome!

**Comment by jonnay** [comment]
Can you somehow force the .scm extension to take precedence over js if it's a s4m node?

**Comment by iainctduncan** [comment]
It's pretty limited what we can do with the editor integration, and it's different on windows. It's unfortunately a bit of a pain part to deal with. I don't think I can do that with the SDK. I could nix the editor integration all together if it proves more hassle than it's worth... not sure what to do there yet.

**Comment by iainctduncan** [comment]
I'd welcome thoughts about the question of whether it's better to just cut it. We could say that a file in the box loads automatically, but axe editor integration. One can always load files by just sending a load message too, so perhaps inconsistent and imperfect behaviour across windows and osx is worse that just not having it? (the double click to open editor, I mean)

**Comment by jonnay** [comment]
Sorry, I too am on OS X!  I think the problem is just whether or not you have "foo.js" and"foo.scm" in the max path (or maybe even the same directory?)

**Comment by iainctduncan** [comment]
Yeah I haven't tested that, I think that should be possible to fix. We will find out!

**Comment by iainctduncan** [comment]
Jon, I am proposing we kill the build in editor integration entirely. I don't think anyone uses it, and it causes a world of pain with the new thread high and low options (from 0.2). Encouraging people to use the built in editor I think will only frustrate them anyway, they need paredit!!

**Comment by iainctduncan** [comment]
closed, editor integration removed, double click now shows full path to file loaded
